# Generated by Django 3.2.7 on 2023-11-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Lagos', max_length=180, verbose_name='City'),
        ),
    ]
