# Generated by Django 3.2.7 on 2023-11-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/generalimage.png', upload_to='', verbose_name='Profile Photo'),
        ),
    ]
