# Generated by Django 3.2.7 on 2023-11-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyviews',
            options={'verbose_name': 'Total Views on Property', 'verbose_name_plural': 'Total Property Views'},
        ),
    ]
